insert into Gruppo (nome_g, descrizione) values ('Construction Worker', null);
insert into Gruppo (nome_g, descrizione) values ('Construction Expeditor', null);
insert into Gruppo (nome_g, descrizione) values ('Electrician', null);
insert into Gruppo (nome_g, descrizione) values ('Estimator', null);
insert into Gruppo (nome_g, descrizione) values ('Construction Worker', null);
insert into Gruppo (nome_g, descrizione) values ('Construction Expeditor', null);
insert into Gruppo (nome_g, descrizione) values ('Construction Foreman', null);
insert into Gruppo (nome_g, descrizione) values ('Construction Foreman', null);
insert into Gruppo (nome_g, descrizione) values ('Architect', null);
insert into Gruppo (nome_g, descrizione) values ('Electrician', null);
insert into Gruppo (nome_g, descrizione) values ('Electrician', null);
insert into Gruppo (nome_g, descrizione) values ('Construction Worker', null);
insert into Gruppo (nome_g, descrizione) values ('Engineer', null);
insert into Gruppo (nome_g, descrizione) values ('Construction Foreman', null);
insert into Gruppo (nome_g, descrizione) values ('Construction Foreman', null);
