insert into Indirizzo (via, citta, cap, nazione) values ('4506 Kim Pass', 'Banjar Dukuh', '83214', 'Indonesia');
insert into Indirizzo (via, citta, cap, nazione) values ('6 Scoville Pass', 'Ciwaru', '77', 'Indonesia');
insert into Indirizzo (via, citta, cap, nazione) values ('58589 Pankratz Road', 'Sacramento', '9249', 'United States');
insert into Indirizzo (via, citta, cap, nazione) values ('86744 Texas Road', 'Khudoyelanskoye', '491', 'Russia');
insert into Indirizzo (via, citta, cap, nazione) values ('1090 Erie Avenue', 'Debrecen', '4', 'Hungary');
insert into Indirizzo (via, citta, cap, nazione) values ('1601 School Parkway', 'Ugep', '78', 'Nigeria');
insert into Indirizzo (via, citta, cap, nazione) values ('81 Sloan Lane', 'Sitovo', '8095', 'Bulgaria');
insert into Indirizzo (via, citta, cap, nazione) values ('6102 Northland Pass', 'Tsalka', '1', 'Georgia');
insert into Indirizzo (via, citta, cap, nazione) values ('4729 Briar Crest Lane', 'Batukuta', '51', 'Indonesia');
insert into Indirizzo (via, citta, cap, nazione) values ('309 Mesta Plaza', 'Fort Worth', '879', 'United States');
insert into Indirizzo (via, citta, cap, nazione) values ('3 Sommers Hill', 'Arles', '0923', 'France');
insert into Indirizzo (via, citta, cap, nazione) values ('43 Leroy Hill', 'Hongsung', '44', 'South Korea');
insert into Indirizzo (via, citta, cap, nazione) values ('1072 Sycamore Avenue', 'Upernavik', '35', 'Greenland');
insert into Indirizzo (via, citta, cap, nazione) values ('42 Haas Park', 'Tianta', '8003', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('5469 Roxbury Crossing', 'Sasovo', '40021', 'Russia');
insert into Indirizzo (via, citta, cap, nazione) values ('010 Cambridge Pass', 'Sélestat', '512', 'France');
insert into Indirizzo (via, citta, cap, nazione) values ('55611 Arapahoe Hill', 'Noda', '33', 'Japan');
insert into Indirizzo (via, citta, cap, nazione) values ('61637 Welch Circle', 'La Paz', '45', 'Uruguay');
insert into Indirizzo (via, citta, cap, nazione) values ('99 Lakewood Gardens Alley', 'Kitapak', '720', 'Philippines');
insert into Indirizzo (via, citta, cap, nazione) values ('863 1st Drive', 'Caitang', '146', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('59441 Evergreen Court', 'Longquan', '58', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('02 Center Way', 'Azogues', '58031', 'Ecuador');
insert into Indirizzo (via, citta, cap, nazione) values ('51 Dryden Pass', 'Majdal Banī Fāḑil', '229', 'Palestinian Territory');
insert into Indirizzo (via, citta, cap, nazione) values ('9 Logan Point', 'Karangturi', '7664', 'Indonesia');
insert into Indirizzo (via, citta, cap, nazione) values ('4 Jenifer Hill', 'Zhuyu', '4826', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('1894 Messerschmidt Terrace', 'Jinjiang', '7051', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('82 Meadow Ridge Plaza', 'Cikaung', '8675', 'Indonesia');
insert into Indirizzo (via, citta, cap, nazione) values ('2 Goodland Drive', 'Santo Domingo', '2', 'Philippines');
insert into Indirizzo (via, citta, cap, nazione) values ('691 Gerald Terrace', 'Rennes', '70', 'France');
insert into Indirizzo (via, citta, cap, nazione) values ('1 Portage Plaza', 'Nuštar', '1854', 'Croatia');
insert into Indirizzo (via, citta, cap, nazione) values ('3 Continental Way', 'Hengling', '9699', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('68 Hanover Plaza', 'Longtanping', '68', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('58809 Fisk Road', 'Geshan', '31588', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('21618 Fulton Center', 'Abobo', '51', 'Ivory Coast');
insert into Indirizzo (via, citta, cap, nazione) values ('633 Birchwood Lane', 'Feyẕābād', '305', 'Iran');
insert into Indirizzo (via, citta, cap, nazione) values ('46 Eggendart Avenue', 'San Felipe', '3', 'Costa Rica');
insert into Indirizzo (via, citta, cap, nazione) values ('11556 Texas Way', 'Gang', '9', 'Philippines');
insert into Indirizzo (via, citta, cap, nazione) values ('55 Glendale Avenue', 'Fenglai', '171', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('510 Clyde Gallagher Point', 'Chonghe', '3', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('0 Stephen Pass', 'Rosh Pinna', '14745', 'Israel');
insert into Indirizzo (via, citta, cap, nazione) values ('097 Jenifer Trail', 'Wādī al ‘Uyūn', '9', 'Syria');
insert into Indirizzo (via, citta, cap, nazione) values ('5 Corry Point', 'Changtang', '11', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('093 Knutson Parkway', 'Damaturu', '3', 'Nigeria');
insert into Indirizzo (via, citta, cap, nazione) values ('1680 Sycamore Way', 'Wilanagara', '62650', 'Indonesia');
insert into Indirizzo (via, citta, cap, nazione) values ('8932 East Alley', 'Khārān', '58690', 'Pakistan');
insert into Indirizzo (via, citta, cap, nazione) values ('33961 Nova Lane', 'Artimet', '917', 'Armenia');
insert into Indirizzo (via, citta, cap, nazione) values ('0 Oneill Court', 'Guanay', '89', 'Bolivia');
insert into Indirizzo (via, citta, cap, nazione) values ('7 Bultman Place', 'Calauag', '09', 'Philippines');
insert into Indirizzo (via, citta, cap, nazione) values ('5601 Grover Alley', 'Fulin', '1829', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('2 American Lane', 'Svojat', '2600', 'Bosnia and Herzegovina');
