insert into Indirizzo (via, citta, cap, nazione) values ('4506 Kim Pass', 'Banjar Dukuh', '83214', 'Indonesia');
insert into Indirizzo (via, citta, cap, nazione) values ('6 Scoville Pass', 'Ciwaru', '77', 'Indonesia');
insert into Indirizzo (via, citta, cap, nazione) values ('58589 Pankratz Road', 'Sacramento', '9249', 'United States');
insert into Indirizzo (via, citta, cap, nazione) values ('86744 Texas Road', 'Khudoyelanskoye', '491', 'Russia');
insert into Indirizzo (via, citta, cap, nazione) values ('1090 Erie Avenue', 'Debrecen', '4', 'Hungary');
insert into Indirizzo (via, citta, cap, nazione) values ('1601 School Parkway', 'Ugep', '78', 'Nigeria');
insert into Indirizzo (via, citta, cap, nazione) values ('81 Sloan Lane', 'Sitovo', '8095', 'Bulgaria');
insert into Indirizzo (via, citta, cap, nazione) values ('6102 Northland Pass', 'Tsalka', '1', 'Georgia');
insert into Indirizzo (via, citta, cap, nazione) values ('4729 Briar Crest Lane', 'Batukuta', '51', 'Indonesia');
insert into Indirizzo (via, citta, cap, nazione) values ('309 Mesta Plaza', 'Fort Worth', '879', 'United States');
insert into Indirizzo (via, citta, cap, nazione) values ('3 Sommers Hill', 'Arles', '0923', 'France');
insert into Indirizzo (via, citta, cap, nazione) values ('43 Leroy Hill', 'Hongsung', '44', 'South Korea');
insert into Indirizzo (via, citta, cap, nazione) values ('1072 Sycamore Avenue', 'Upernavik', '35', 'Greenland');
insert into Indirizzo (via, citta, cap, nazione) values ('42 Haas Park', 'Tianta', '8003', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('5469 Roxbury Crossing', 'Sasovo', '40021', 'Russia');
insert into Indirizzo (via, citta, cap, nazione) values ('010 Cambridge Pass', 'Sélestat', '512', 'France');
insert into Indirizzo (via, citta, cap, nazione) values ('55611 Arapahoe Hill', 'Noda', '33', 'Japan');
insert into Indirizzo (via, citta, cap, nazione) values ('61637 Welch Circle', 'La Paz', '45', 'Uruguay');
insert into Indirizzo (via, citta, cap, nazione) values ('99 Lakewood Gardens Alley', 'Kitapak', '720', 'Philippines');
insert into Indirizzo (via, citta, cap, nazione) values ('863 1st Drive', 'Caitang', '146', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('59441 Evergreen Court', 'Longquan', '58', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('02 Center Way', 'Azogues', '58031', 'Ecuador');
insert into Indirizzo (via, citta, cap, nazione) values ('51 Dryden Pass', 'Majdal Banī Fāḑil', '229', 'Palestinian Territory');
insert into Indirizzo (via, citta, cap, nazione) values ('9 Logan Point', 'Karangturi', '7664', 'Indonesia');
insert into Indirizzo (via, citta, cap, nazione) values ('4 Jenifer Hill', 'Zhuyu', '4826', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('1894 Messerschmidt Terrace', 'Jinjiang', '7051', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('82 Meadow Ridge Plaza', 'Cikaung', '8675', 'Indonesia');
insert into Indirizzo (via, citta, cap, nazione) values ('2 Goodland Drive', 'Santo Domingo', '2', 'Philippines');
insert into Indirizzo (via, citta, cap, nazione) values ('691 Gerald Terrace', 'Rennes', '70', 'France');
insert into Indirizzo (via, citta, cap, nazione) values ('1 Portage Plaza', 'Nuštar', '1854', 'Croatia');
insert into Indirizzo (via, citta, cap, nazione) values ('3 Continental Way', 'Hengling', '9699', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('68 Hanover Plaza', 'Longtanping', '68', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('58809 Fisk Road', 'Geshan', '31588', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('21618 Fulton Center', 'Abobo', '51', 'Ivory Coast');
insert into Indirizzo (via, citta, cap, nazione) values ('633 Birchwood Lane', 'Feyẕābād', '305', 'Iran');
insert into Indirizzo (via, citta, cap, nazione) values ('46 Eggendart Avenue', 'San Felipe', '3', 'Costa Rica');
insert into Indirizzo (via, citta, cap, nazione) values ('11556 Texas Way', 'Gang', '9', 'Philippines');
insert into Indirizzo (via, citta, cap, nazione) values ('55 Glendale Avenue', 'Fenglai', '171', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('510 Clyde Gallagher Point', 'Chonghe', '3', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('0 Stephen Pass', 'Rosh Pinna', '14745', 'Israel');
insert into Indirizzo (via, citta, cap, nazione) values ('097 Jenifer Trail', 'Wādī al ‘Uyūn', '9', 'Syria');
insert into Indirizzo (via, citta, cap, nazione) values ('5 Corry Point', 'Changtang', '11', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('093 Knutson Parkway', 'Damaturu', '3', 'Nigeria');
insert into Indirizzo (via, citta, cap, nazione) values ('1680 Sycamore Way', 'Wilanagara', '62650', 'Indonesia');
insert into Indirizzo (via, citta, cap, nazione) values ('8932 East Alley', 'Khārān', '58690', 'Pakistan');
insert into Indirizzo (via, citta, cap, nazione) values ('33961 Nova Lane', 'Artimet', '917', 'Armenia');
insert into Indirizzo (via, citta, cap, nazione) values ('0 Oneill Court', 'Guanay', '89', 'Bolivia');
insert into Indirizzo (via, citta, cap, nazione) values ('7 Bultman Place', 'Calauag', '09', 'Philippines');
insert into Indirizzo (via, citta, cap, nazione) values ('5601 Grover Alley', 'Fulin', '1829', 'China');
insert into Indirizzo (via, citta, cap, nazione) values ('2 American Lane', 'Svojat', '2600', 'Bosnia and Herzegovina');

insert into Contatto (nome, cognome, indirizzo_p) values ('Norma', 'Boyle', 11);
insert into Contatto (nome, cognome, indirizzo_p) values ('Christel', 'Pennone', 45);
insert into Contatto (nome, cognome, indirizzo_p) values ('Carline', 'Sheere', 9);
insert into Contatto (nome, cognome, indirizzo_p) values ('Chrotoem', 'Maycock', 38);
insert into Contatto (nome, cognome, indirizzo_p) values ('Halli', 'Le Brom', 31);
insert into Contatto (nome, cognome, indirizzo_p) values ('Jarrett', 'Elward', 42);
insert into Contatto (nome, cognome, indirizzo_p) values ('Morse', 'Burle', 46);
insert into Contatto (nome, cognome, indirizzo_p) values ('Danette', 'O''Hoey', 35);
insert into Contatto (nome, cognome, indirizzo_p) values ('Jenelle', 'McEneny', 49);
insert into Contatto (nome, cognome, indirizzo_p) values ('Benji', 'Eastbury', 41);
insert into Contatto (nome, cognome, indirizzo_p) values ('Lamont', 'Kynder', 35);
insert into Contatto (nome, cognome, indirizzo_p) values ('Fred', 'Huburn', 11);
insert into Contatto (nome, cognome, indirizzo_p) values ('Lorry', 'Skippon', 41);
insert into Contatto (nome, cognome, indirizzo_p) values ('Jesselyn', 'Saylor', 9);
insert into Contatto (nome, cognome, indirizzo_p) values ('Dorie', 'Elman', 9);
insert into Contatto (nome, cognome, indirizzo_p) values ('Sukey', 'Bessett', 12);
insert into Contatto (nome, cognome, indirizzo_p) values ('Georgie', 'Brimble', 50);
insert into Contatto (nome, cognome, indirizzo_p) values ('Fanya', 'Kroger', 37);
insert into Contatto (nome, cognome, indirizzo_p) values ('Godiva', 'Burds', 1);
insert into Contatto (nome, cognome, indirizzo_p) values ('Diarmid', 'Linfield', 4);
insert into Contatto (nome, cognome, indirizzo_p) values ('Hendrick', 'Kubicek', 42);
insert into Contatto (nome, cognome, indirizzo_p) values ('Fiann', 'Sadlier', 21);
insert into Contatto (nome, cognome, indirizzo_p) values ('Janie', 'Conaghan', 18);
insert into Contatto (nome, cognome, indirizzo_p) values ('Foss', 'Baldcock', 1);
insert into Contatto (nome, cognome, indirizzo_p) values ('Liesa', 'Coopland', 26);
insert into Contatto (nome, cognome, indirizzo_p) values ('Gian', 'Casaccio', 48);
insert into Contatto (nome, cognome, indirizzo_p) values ('Charisse', 'Dillaway', 33);
insert into Contatto (nome, cognome, indirizzo_p) values ('Pattie', 'Fernie', 1);
insert into Contatto (nome, cognome, indirizzo_p) values ('Brooks', 'Flintoff', 46);
insert into Contatto (nome, cognome, indirizzo_p) values ('Percy', 'Hestrop', 38);

insert into Telefono (numero, prefisso, tipo) values ('417078072', '89', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('212553526', '51', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('030984340', '16', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('522741123', '72', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('411231038', '75', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('487250997', '62', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('248608175', '59', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('352635303', '87', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('019134679', '36', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('880572957', '15', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('875287184', '76', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('900112843', '26', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('232291165', '33', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('082070312', '34', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('324630949', '22', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('676235416', '21', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('841411164', '08', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('206919947', '21', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('045270886', '36', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('528722686', '70', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('599016492', '33', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('873084469', '78', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('386022206', '44', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('685932757', '00', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('458943202', '74', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('809359374', '41', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('358553289', '08', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('815827385', '22', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('059997958', '28', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('779378678', '57', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('824197418', '17', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('217988992', '42', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('382931983', '58', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('656335671', '36', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('029550628', '56', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('895032244', '41', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('761494395', '95', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('130160853', '54', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('513595816', '51', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('065554967', '11', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('310921517', '52', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('987834004', '47', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('829433132', '06', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('096734026', '36', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('902044158', '51', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('793932061', '83', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('064664176', '27', 'Fisso');
insert into Telefono (numero, prefisso, tipo) values ('369333293', '17', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('109336082', '87', 'Mobile');
insert into Telefono (numero, prefisso, tipo) values ('805756416', '05', 'Fisso');

insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (1, '068164872', '45', '205235026', '73');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (2, '660377796', '18', '938042359', '48');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (3, '988458404', '56', '729033918', '22');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (4, '541535860', '10', '466224171', '59');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (5, '872755638', '41', '498370529', '96');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (6, '010832822', '36', '382172879', '69');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (7, '447016725', '15', '595910776', '03');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (8, '807019304', '37', '402915875', '68');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (9, '464874040', '45', '036097876', '09');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (10, '398273667', '48', '927371642', '47');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (11, '795818071', '36', '775232532', '56');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (12, '866633416', '75', '811798900', '50');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (13, '096303552', '52', '133040748', '19');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (14, '031193222', '51', '143006845', '33');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (15, '126554866', '09', '938146883', '94');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (1, '205235026', '73', '068164872', '45');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (2, '938042359', '48', '660377796', '18');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (3, '729033918', '22', '988458404', '56');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (4, '466224171', '59', '541535860', '10');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (5, '498370529', '96', '872755638', '41');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (6, '382172879', '69', '010832822', '36');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (7, '595910776', '03', '447016725', '15');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (8, '402915875', '68', '807019304', '37');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (9, '036097876', '09', '464874040', '45');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (10, '927371642', '47', '398273667', '48');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (11, '775232532', '56', '795818071', '36');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (12, '811798900', '50', '866633416', '75');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (13, '133040748', '19', '096303552', '52');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (14, '143006845', '33', '031193222', '51');
insert into Recapito (cont_id, numero, prefisso, numero_out, prefisso_out) values (15, '938146883', '94', '126554866', '09');

insert into Gruppo (nome_g, descrizione) values ('Construction Worker', null);
insert into Gruppo (nome_g, descrizione) values ('Construction Expeditor', null);
insert into Gruppo (nome_g, descrizione) values ('Electrician', null);
insert into Gruppo (nome_g, descrizione) values ('Estimator', null);
insert into Gruppo (nome_g, descrizione) values ('Construction Worker', null);
insert into Gruppo (nome_g, descrizione) values ('Construction Expeditor', null);
insert into Gruppo (nome_g, descrizione) values ('Construction Foreman', null);
insert into Gruppo (nome_g, descrizione) values ('Construction Foreman', null);
insert into Gruppo (nome_g, descrizione) values ('Architect', null);
insert into Gruppo (nome_g, descrizione) values ('Electrician', null);
insert into Gruppo (nome_g, descrizione) values ('Electrician', null);
insert into Gruppo (nome_g, descrizione) values ('Construction Worker', null);
insert into Gruppo (nome_g, descrizione) values ('Engineer', null);
insert into Gruppo (nome_g, descrizione) values ('Construction Foreman', null);
insert into Gruppo (nome_g, descrizione) values ('Construction Foreman', null);

insert into Alloggio (addr_id, cont_id) values (47, 13);
insert into Alloggio (addr_id, cont_id) values (49, 13);
insert into Alloggio (addr_id, cont_id) values (38, 3);
insert into Alloggio (addr_id, cont_id) values (26, 22);
insert into Alloggio (addr_id, cont_id) values (43, 13);
insert into Alloggio (addr_id, cont_id) values (28, 1);
insert into Alloggio (addr_id, cont_id) values (44, 8);
insert into Alloggio (addr_id, cont_id) values (25, 29);
insert into Alloggio (addr_id, cont_id) values (3, 4);
insert into Alloggio (addr_id, cont_id) values (20, 23);
insert into Alloggio (addr_id, cont_id) values (8, 7);
insert into Alloggio (addr_id, cont_id) values (34, 11);
insert into Alloggio (addr_id, cont_id) values (20, 10);
insert into Alloggio (addr_id, cont_id) values (20, 23);
insert into Alloggio (addr_id, cont_id) values (8, 14);
insert into Alloggio (addr_id, cont_id) values (1, 11);
insert into Alloggio (addr_id, cont_id) values (2, 45);
insert into Alloggio (addr_id, cont_id) values (3, 9);
insert into Alloggio (addr_id, cont_id) values (4, 38);
insert into Alloggio (addr_id, cont_id) values (5, 31);
insert into Alloggio (addr_id, cont_id) values (6, 42);
insert into Alloggio (addr_id, cont_id) values (7, 46);
insert into Alloggio (addr_id, cont_id) values (8, 35);
insert into Alloggio (addr_id, cont_id) values (9, 49);
insert into Alloggio (addr_id, cont_id) values (10, 41);
insert into Alloggio (addr_id, cont_id) values (11, 35);
insert into Alloggio (addr_id, cont_id) values (12, 11);
insert into Alloggio (addr_id, cont_id) values (13, 41);
insert into Alloggio (addr_id, cont_id) values (14, 9);
insert into Alloggio (addr_id, cont_id) values (15, 9);
insert into Alloggio (addr_id, cont_id) values (16, 12);
insert into Alloggio (addr_id, cont_id) values (17, 50);
insert into Alloggio (addr_id, cont_id) values (18, 37);
insert into Alloggio (addr_id, cont_id) values (19, 1);
insert into Alloggio (addr_id, cont_id) values (20, 4);
insert into Alloggio (addr_id, cont_id) values (21, 42);
insert into Alloggio (addr_id, cont_id) values (22, 21);
insert into Alloggio (addr_id, cont_id) values (23, 18);
insert into Alloggio (addr_id, cont_id) values (24, 1);
insert into Alloggio (addr_id, cont_id) values (25, 26);
insert into Alloggio (addr_id, cont_id) values (26, 48);
insert into Alloggio (addr_id, cont_id) values (27, 33);
insert into Alloggio (addr_id, cont_id) values (28, 1);
insert into Alloggio (addr_id, cont_id) values (29, 46);
insert into Alloggio (addr_id, cont_id) values (30, 38);

insert into Aggregazione (group_id, cont_id) values (6, 13);
insert into Aggregazione (group_id, cont_id) values (8, 6);
insert into Aggregazione (group_id, cont_id) values (11, 14);
insert into Aggregazione (group_id, cont_id) values (10, 8);
insert into Aggregazione (group_id, cont_id) values (8, 28);
insert into Aggregazione (group_id, cont_id) values (3, 2);
insert into Aggregazione (group_id, cont_id) values (12, 7);
insert into Aggregazione (group_id, cont_id) values (1, 3);
insert into Aggregazione (group_id, cont_id) values (3, 29);
insert into Aggregazione (group_id, cont_id) values (6, 22);
insert into Aggregazione (group_id, cont_id) values (8, 5);
insert into Aggregazione (group_id, cont_id) values (13, 6);
insert into Aggregazione (group_id, cont_id) values (12, 3);
insert into Aggregazione (group_id, cont_id) values (11, 7);
insert into Aggregazione (group_id, cont_id) values (8, 9);
insert into Aggregazione (group_id, cont_id) values (8, 20);
insert into Aggregazione (group_id, cont_id) values (6, 25);
insert into Aggregazione (group_id, cont_id) values (2, 10);
insert into Aggregazione (group_id, cont_id) values (11, 19);
insert into Aggregazione (group_id, cont_id) values (10, 17);
insert into Aggregazione (group_id, cont_id) values (6, 1);
insert into Aggregazione (group_id, cont_id) values (5, 30);
insert into Aggregazione (group_id, cont_id) values (9, 6);
insert into Aggregazione (group_id, cont_id) values (1, 18);
insert into Aggregazione (group_id, cont_id) values (12, 8);
insert into Aggregazione (group_id, cont_id) values (2, 15);
insert into Aggregazione (group_id, cont_id) values (3, 15);
insert into Aggregazione (group_id, cont_id) values (12, 27);
insert into Aggregazione (group_id, cont_id) values (11, 28);
insert into Aggregazione (group_id, cont_id) values (14, 4);

insert into Email (indirizzo, utilizzo, cont_id) values ('ahrishchenko0@bizjournals.com', null, 1);
insert into Email (indirizzo, utilizzo, cont_id) values ('kstodart1@istockphoto.com', null, 2);
insert into Email (indirizzo, utilizzo, cont_id) values ('sconfait2@amazon.com', null, 3);
insert into Email (indirizzo, utilizzo, cont_id) values ('llermit3@wired.com', null, 4);
insert into Email (indirizzo, utilizzo, cont_id) values ('hhusby4@amazon.com', null, 5);
insert into Email (indirizzo, utilizzo, cont_id) values ('alowther5@pcworld.com', null, 6);
insert into Email (indirizzo, utilizzo, cont_id) values ('klawille6@prweb.com', null, 7);
insert into Email (indirizzo, utilizzo, cont_id) values ('hbertie7@symantec.com', null, 8);
insert into Email (indirizzo, utilizzo, cont_id) values ('hskegg8@sourceforge.net', null, 9);
insert into Email (indirizzo, utilizzo, cont_id) values ('gsawell9@opensource.org', null, 10);
insert into Email (indirizzo, utilizzo, cont_id) values ('bcoraina@sitemeter.com', null, 11);
insert into Email (indirizzo, utilizzo, cont_id) values ('tpipworthb@admin.ch', null, 12);
insert into Email (indirizzo, utilizzo, cont_id) values ('kmealingc@sciencedirect.com', null, 13);
insert into Email (indirizzo, utilizzo, cont_id) values ('ckeseyd@instagram.com', null, 14);
insert into Email (indirizzo, utilizzo, cont_id) values ('mgwaltere@yolasite.com', null, 15);
insert into Email (indirizzo, utilizzo, cont_id) values ('credholef@github.com', null, 16);
insert into Email (indirizzo, utilizzo, cont_id) values ('bcodnerg@ebay.co.uk', null, 17);
insert into Email (indirizzo, utilizzo, cont_id) values ('fsangwinh@businessweek.com', null, 18);
insert into Email (indirizzo, utilizzo, cont_id) values ('smottoi@discovery.com', null, 19);
insert into Email (indirizzo, utilizzo, cont_id) values ('ngallj@last.fm', null, 20);
insert into Email (indirizzo, utilizzo, cont_id) values ('bgosbyk@lycos.com', null, 21);
insert into Email (indirizzo, utilizzo, cont_id) values ('awhenhaml@live.com', null, 22);
insert into Email (indirizzo, utilizzo, cont_id) values ('hpoorem@unc.edu', null, 23);
insert into Email (indirizzo, utilizzo, cont_id) values ('ucamillin@dell.com', null, 24);
insert into Email (indirizzo, utilizzo, cont_id) values ('mwarmingtono@fotki.com', null, 25);
insert into Email (indirizzo, utilizzo, cont_id) values ('lvolksp@yahoo.com', null, 26);
insert into Email (indirizzo, utilizzo, cont_id) values ('ilacroceq@goodreads.com', null, 27);
insert into Email (indirizzo, utilizzo, cont_id) values ('lchengr@dedecms.com', null, 28);
insert into Email (indirizzo, utilizzo, cont_id) values ('btulls@arstechnica.com', null, 29);
insert into Email (indirizzo, utilizzo, cont_id) values ('slocknert@google.co.uk', null, 30);

insert into MessagingPR (nickname, frase_benvenuto, fornitore, indirizzo) values ('ogercken0', 'Vision-oriented needs-based knowledge user', 'Aerified', 'fhuffa0@liveinternet.ru');
insert into MessagingPR (nickname, frase_benvenuto, fornitore, indirizzo) values ('gtretwell1', 'Quality-focused coherent local area network', 'Veribet', 'dguiver1@typepad.com');
insert into MessagingPR (nickname, frase_benvenuto, fornitore, indirizzo) values ('eohenehan2', 'Synchronised regional customer loyalty', 'Wrapsafe', 'jorman2@bloglines.com');
insert into MessagingPR (nickname, frase_benvenuto, fornitore, indirizzo) values ('nbroodes3', 'Open-architected web-enabled instruction set', 'Bitchip', 'tgagin3@gmpg.org');
insert into MessagingPR (nickname, frase_benvenuto, fornitore, indirizzo) values ('wpontefract4', 'Visionary heuristic definition', 'Namfix', 'estanyland4@canalblog.com');
insert into MessagingPR (nickname, frase_benvenuto, fornitore, indirizzo) values ('lclymer5', 'Fully-configurable leading edge process improvement', 'Job', 'vupjohn5@cocolog-nifty.com');
insert into MessagingPR (nickname, frase_benvenuto, fornitore, indirizzo) values ('strumper6', 'Triple-buffered mobile success', 'Zontrax', 'ckrojn6@sourceforge.net');
insert into MessagingPR (nickname, frase_benvenuto, fornitore, indirizzo) values ('wgreenrod7', 'Robust holistic software', 'Tresom', 'alawlie7@guardian.co.uk');
insert into MessagingPR (nickname, frase_benvenuto, fornitore, indirizzo) values ('cloram8', 'Streamlined scalable archive', 'Bigtax', 'sabramovici8@economist.com');
insert into MessagingPR (nickname, frase_benvenuto, fornitore, indirizzo) values ('jfontin9', 'Vision-oriented non-volatile archive', 'Konklux', 'anapton9@msn.com');
insert into MessagingPR (nickname, frase_benvenuto, fornitore, indirizzo) values ('glidyarda', 'Synergized national moderator', 'Regrant', 'mpinwella@npr.org');
insert into MessagingPR (nickname, frase_benvenuto, fornitore, indirizzo) values ('bsarginsonb', 'Digitized asymmetric analyzer', 'Flexidy', 'jdymickb@360.cn');
insert into MessagingPR (nickname, frase_benvenuto, fornitore, indirizzo) values ('tphetteplacec', 'Mandatory contextually-based artificial intelligence', 'Sub-Ex', 'smaronc@booking.com');
insert into MessagingPR (nickname, frase_benvenuto, fornitore, indirizzo) values ('dcunneyd', 'Virtual modular firmware', 'Quo Lux', 'spittendreighd@woothemes.com');
insert into MessagingPR (nickname, frase_benvenuto, fornitore, indirizzo) values ('ebiermatowicze', 'Cross-group encompassing strategy', 'Lotstring', 'arobardete@blogspot.com');
insert into MessagingPR (nickname, frase_benvenuto, fornitore, indirizzo) values ('dpennycordf', 'Programmable client-server process improvement', 'Kanlam', 'bmcgurkf@yahoo.com');
insert into MessagingPR (nickname, frase_benvenuto, fornitore, indirizzo) values ('elaxeng', 'Fundamental non-volatile emulation', 'Span', 'mmegaheyg@cam.ac.uk');
insert into MessagingPR (nickname, frase_benvenuto, fornitore, indirizzo) values ('vbarkush', 'Polarised holistic initiative', 'Fixflex', 'jfarakerh@apple.com');
insert into MessagingPR (nickname, frase_benvenuto, fornitore, indirizzo) values ('cchevisi', 'Distributed next generation pricing structure', 'Flowdesk', 'smugfordi@domainmarket.com');
insert into MessagingPR (nickname, frase_benvenuto, fornitore, indirizzo) values ('rfleischmannj', 'De-engineered system-worthy service-desk', 'Latlux', 'mmullerj@answers.com');
