CREATE OR REPLACE FUNCTION controllo_delete_recapiti() RETURNS TRIGGER AS $controllo_delete_recapiti_trigger$

DECLARE

MOBILE INT := 0;
FISSO INT := 0;
TIPO TELEFONO.TIPO%TYPE;


BEGIN

SELECT TEL.TIPO INTO TIPO FROM TELEFONO AS TEL WHERE TEL.NUMERO=OLD.NUMERO AND TEL.PREFISSO = OLD.PREFISSO;

SELECT COUNT(*) INTO MOBILE FROM RECAPITO AS R JOIN TELEFONO AS TEL ON R.NUMERO=TEL.NUMERO AND R.PREFISSO=TEL.PREFISSO WHERE OLD.CONT_ID = R.CONT_ID AND TEL.TIPO = 'Mobile';
SELECT COUNT(*) INTO FISSO FROM RECAPITO AS R JOIN TELEFONO AS TEL ON R.NUMERO=TEL.NUMERO AND R.PREFISSO=TEL.PREFISSO WHERE OLD.CONT_ID = R.CONT_ID AND TEL.TIPO = 'Fisso';

IF (TIPO = 'Mobile' AND MOBILE < 2 ) OR (TIPO = 'Fisso' AND FISSO < 2 )   THEN
RAISE EXCEPTION 'Deve esserci almeno un mobile e un fisso!' USING ERRCODE = '23000';
END IF;
END;


$controllo_delete_recapiti_trigger$

LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER controllo_delete_recapiti_trigger BEFORE DELETE ON RECAPITO

FOR EACH ROW EXECUTE FUNCTION controllo_delete_recapiti();
